es\layout\activity_main.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="primary">#1A237E</color>
    <color name="primary_dark">#1a237e</color>
    <color name="primary_light">#E8EAF6</color>
    <color name="accent">#4caf50</color>
    <color name="accent_dark">#2e7d32</color>
    <color name="error">#f44336</color>
    <color name="error_light">#ffebee</color>
    <color name="success">#4caf50</color>
    <color name="success_light">#e8f5e9</color>
    <color name="cell_border">#1a237e</color>
    <color name="cell_selected">#2196f3</color>
    <color name="cell_background">@android:color/white</color>
    <color name="text_primary">#1A237E</color>
    <color name="text_secondary">#e0e0e0</color>
    <color name="background">#F0F2F5</color>
    <color name="button_blue">#2196F3</color>
    <color name="button_green">#4CAF50</color>
    <color name="grid_header">#E3F2FD</color>
    <color name="grid_border">#1A237E</color>
    <color name="clue_background">#424242</color>
    <color name="clue_text">#E3F2FD</color>
    <color name="white">#FFFFFF</color>
    <color name="level_background">#E3F2FD</color>
    <color name="level_text">#1565C0</color>
    
    <!-- New colors for enhanced grid -->
    <color name="grid_background">#FFFFFF</color>
    <color name="header_background">#3F51B5</color>
    <color name="header_text">#FFFFFF</color>
    <color name="cell_yes">#E8F5E9</color>
    <color name="cell_no">#FFEBEE</color>
    <color name="cell_empty">#FAFAFA</color>
    <color name="clue_card_background">#303F9F</color>
    <color name="clue_item_background">#E8EAF6</color>
    <color name="clue_item_text">#303F9F</color>
</resources>
<androidx.cardview.widget.CardView
    android:id="@+id/cluesCard"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="16dp"
    app:cardBackgroundColor="@color/clue_card_background"
    app:cardCornerRadius="12dp"
    app:cardElevation="8dp"
    app:layout_constraintTop_toBottomOf="@id/gridLayout">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:padding="16dp">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/clues_title"
            android:textColor="@color/white"
            android:textSize="20sp"
            android:textStyle="bold"
            android:layout_marginBottom="12dp" />

        <LinearLayout
            android:id="@+id/cluesList"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:padding="8dp" />
    </LinearLayout>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</androidx.cardview.widget.CardView>
</